server:
  port: 8010
spring:
  application:
    name: product-management
  datasource:
    url: jdbc:postgresql://localhost:5436/productdb
    username: productdbuser
    password: Login@123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  # config:
  #   import:
  #     -"product-management_prod.yml"
  #     -"product-management_qa.yml"
  # profiles:
  #   active: "qa"    