server:
  port: 8020
spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://userdb.cn8ceqos04go.eu-north-1.rds.amazonaws.com:5434/UserDB
    username: postgres
    password: Login#1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # config:
  #   import:
  #     -"user-management_prod.yml"
  #     -"user-management_qa.yml"
  # profiles:
  #   active: "qa"
