server:
  port: 8020
spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5434/userdb
    username: userdbuser
    password: Login@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # config:
  #   import:
  #     -"user-management_prod.yml"
  #     -"user-management_qa.yml"
  # profiles:
  #   active: "qa"
